const auth_actions = {
  SIGNIN_SUCCESSFUL: 'SIGNIN_SUCCESSFUL',
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNIN_FAILED: 'SIGNIN_FAILED',

  FORGOT_PASSWORD_SUCCESSFUL: 'FORGOT_PASSWORD_SUCCESSFUL',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED',

  PASSWORD_RESET_SUCCESSFUL: 'PASSWORD_RESET_SUCCESSFUL',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',

  GET_EMAIL_LINK_SUCCESSFUL: 'GET_EMAIL_LINK_SUCCESSFUL',
  GET_EMAIL_LINK_REQUEST: 'GET_EMAIL_LINK_REQUEST',
  GET_EMAIL_LINK_FAILED: 'GET_EMAIL_LINK_FAILED',

  VERIFY_TOKEN_SUCCESSFUL: 'VERIFY_TOKEN_SUCCESSFUL',
  VERIFY_TOKEN_REQUEST: 'VERIFY_TOKEN_REQUEST',
  VERIFY_TOKEN_FAILED: 'VERIFY_TOKEN_FAILED',

  VERIFY_EMAIL_SUCCESSFUL: 'VERIFY_EMAIL_SUCCESSFUL',
  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_FAILED: 'VERIFY_EMAIL_FAILED',

  SIGNUP_SUCCESSFUL: 'SIGNUP_SUCCESSFUL',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  UPDATE_SUCCESSFUL: 'UPDATE_SUCCESSFUL',
  UPDATE_REQUEST: 'UPDATE_REQUEST',
  UPDATE_FAILED: 'UPDATE_FAILED',

  SIGNOUT: 'SIGNOUT',
};

export default auth_actions;
