export default {
  GET_FISHES_SUCCESSFUL: 'GET_FISHES_SUCCESSFUL',
  GET_FISHES_REQUEST: 'GET_FISHES_REQUEST',
  GET_FISHES_FAILED: 'GET_FISHES_FAILED',

  GET_FISH_SUCCESSFUL: 'GET_FISH_SUCCESSFUL',
  GET_FISH_REQUEST: 'GET_FISH_REQUEST',
  GET_FISH_FAILED: 'GET_FISH_FAILED',

  DELETE_FISH_SUCCESSFUL: 'DELETE_FISH_SUCCESSFUL',
  DELETE_FISH_REQUEST: 'DELETE_FISH_REQUEST',
  DELETE_FISH_FAILED: 'DELETE_FISH_FAILED',

  UPDATE_FISH_SUCCESSFUL: 'UPDATE_FISH_SUCCESSFUL',
  UPDATE_FISH_REQUEST: 'UPDATE_FISH_REQUEST',
  UPDATE_FISH_FAILED: 'UPDATE_FISH_FAILED',

  ADD_FISH_SUCCESSFUL: 'ADD_FISH_SUCCESSFUL',
  ADD_FISH_REQUEST: 'ADD_FISH_REQUEST',
  ADD_FISH_FAILED: 'ADD_FISH_FAILED',
};
